
name: CI1
env:
  BUCKET_NAME : "neha-bucket123"
  APP_NAME : "neha-app"
  ENV_NAME : "Nehaapp-env"
  PACKAGE_NAME : "neha-${{ github.sha }}.zip"
  AWS_REGION : "us-east-2"

on:
  push:
    branches: [ master ]

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Create zip
        run: zip -r ${{ env.PACKAGE_NAME }} ./ -x "*.git"
      
      # Get credentials
      - name: get temp credentials
        run: echo ::set-output name=CREDENTIALS::$(aws sts assume-role-with-web-identity  --role-arn 'arn:aws:iam::151347512159:role/S3FullAccessV3-OIDCDemo' --role-session-name 'samplerolesession' --web-identity-token 'eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FudXBhZGgubmdyb2suaW8iLCJpYXQiOjE2MjM5MzMyMDgsImV4cCI6MTYyNDExNzExMCwiYXVkIjoiZ2hhY3Rpb25zIiwic3ViIjoicmVwbzpuYXZpbjIyL2dpdGh1Yi1hY3Rpb25zLXBhcnQyLWNpY2QtdG8tYXdzOmJyYW5jaDptYWluIn0.JWias1FXQXxBLR6uAxD44aAuElJTBFzUd7Ca7Pg1DvndpTeOm_fnz_m5cG7-8YwM6tRxP9My7n1VTZ3T-6xjzZFqv0k7sq_MnLr2Ot9aO36igIjpA9gRsoyMjKbIkySqVlK5SYXrnMCAGyiaX96a-Q7IOMyw7AP50SmS0auksYlYhD-WisXxGjR_FzcJysGgVkZmIOmsbJ9BNsz_6Zn1gohgOXY7ImKYJl8LwyFwB_LPIdaqL5F78Tr31EkByWy2oSfcJvImx5uLnJnpL3cNPJ7Orus9_eeYctOjvwhrw0K1OebL-1kLcL0bkiN6LhOyyaLcOLexIdNx62g1dYvraw' --query Credentials)
        id: credentials
        
      - name: get access ID
        run: echo ::set-output name=ACCESSID::$(echo '${{ steps.credentials.outputs.CREDENTIALS }}' | jq -rc '.AccessKeyId')
        id: accessid
        
      - name: get access key
        run: echo ::set-output name=ACCESSKEY::$(echo '${{ steps.credentials.outputs.CREDENTIALS }}' | jq -rc '.SecretAccessKey')
        id: accesskey
        
      - name: get session token
        run: echo ::set-output name=SESSIONTOKEN::$(echo '${{ steps.credentials.outputs.CREDENTIALS }}' | jq -rc '.SessionToken')
        id: sessiontoken
      
      # Runs a set of commands using the runners shell
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ steps.accessid.outputs.ACCESSID }}
          aws-secret-access-key: ${{ steps.accesskey.outputs.ACCESSKEY }}
          aws-session-token: ${{ steps.sessiontoken.outputs.SESSIONTOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name:  Copy package to s3
        run: aws s3 cp ${{ env.PACKAGE_NAME }} s3://${{ env.BUCKET_NAME }}/
